### PR TITLE
Add example for three buttons

### PR DESCRIPTION
**Pull request by gverni**
Inspired by @zenflow's suggestion for https://github.com/sweetalert2/sweetalert2/issues/1881

### CODE REVIEW

**Comment by gverni** [comment]
@limonte @zenflow let me know if you are fine with adding this to the examples. I think it's a very good example of how to extend `Swal`. What do you think?

**Comment by alexandremix** [comment]
> I was always confused by dialogs with 3 buttons, especially with "No" and "Cancel" buttons 😆
> 
> This example is the good demonstration of the technical side (enhancer), but the bad demonstration of UX. Also, some APIs (`focusCancel`, `focusConfirm`) are not respected and the default a11y functionality related to focus is not working (the confirm button isn't focused by default).

In paint, the Save, Don't save, and cancel confuses you? 

if there's a question Delete, don't delete, cancel confuses you?

Add to cart, remove to cart, and cancel. confuses you? 

Don't look at this as a Yes and a no. Look at this as a Do, undo, Do nothing. 

I don't understand your hate on this... Because you don't "Like it.." Or cant understand what the computer is asking you. 

for me every question is quite obvious and understandable. 

what would you like to do? 
Aprove file, disapprove File, Do Do nothing for now. Or Ask Later. 
whatever, I could be here all day to be honest... 

Bad UX. so lets make a radio button? Lets see the bad UX disavantages of that. 

1. If the first radio is selected, the user could misspress ok without having to actualy choose a option. Making more easy a error to occur. 
2. If no radio is selected, the user has to always, press 1 time to choose the option and a second time to press ok. 
3. Theres 4 buttons on the screen making more dificult to understand what it going on. 

4. A user presses a option on the radio button and then presses the cancel button by mistake. Its confusing, to know for sure what he did. He can think he chose that option. 

Lets remind us that every user that uses a computer is not a expert (programer) like all of us... they can get easily confused with all this options. You all have a mom at home that gets confused with simple things .. 

Please understand what I am telling you, and stop trying to be right about this... open up your mind here. Your bias is getting in the way.

**Comment by limonte** [comment]
I do not like this example because it'll break existed APIs and keyboard a11y as mentioned previously:

> some APIs (focusCancel, focusConfirm) are not respected and the default a11y functionality related to focus is not working (the confirm button isn't focused by default).

I'll come up with another example in https://github.com/sweetalert2/sweetalert2.github.io/issues/112

**Comment by limonte** [comment]
I'll block @alexandremix per our [code of conduct](https://github.com/sweetalert2/sweetalert2/blob/master/.github/CODE_OF_CONDUCT.md)

> Examples of unacceptable behavior by participants include the use of sexual language or imagery, derogatory comments or personal attacks, trolling, public or private harassment, insults, or other unprofessional conduct.

**Pull request closed without merging**
